name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --ci
      # - name: Run Stryker
      #   run: npx stryker run
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.0.0
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
